language: python

python:
- "3.8"
- "3.9"

before_install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy
  - pip install typing-extensions
  - pip install git+https://github.com/pnsaevik/ladim.git

install:
  - pip install .
  - pip list

script:
  - pytest -Wignore
